GET http://localhost:3000/todo HTTP/1.1

####
POST http://localhost:3000/todo HTTP/1.1
Content-Type: application/json

{
    "title": "Well.. it's done",
    "description": "Yes.. it is"
}


####
PUT http://localhost:3000/todo/637d2c84349441608d361656 HTTP/1.1
Content-Type: application/json

{
    "title": "Mop",
    "description": "Mop upstairs"
}


####
DELETE http://localhost:3000/todo/637d2e3f67ab813c69d67ce2 HTTP/1.1